export const products = JSON.parse(localStorage.getItem("products"));
// [
//   {
//     id: 1,
//     isLiked: true,
//     img: "imgs/t_product_540_high.jpg (12).png",
//     title: ` Kungaboqar yog'i Oila tanlovi, tozalangan va xidsizlantirilgan, 90…`,
//     reting: "4",
//     real_price: "15 000 so'm",
//     discount_price: "13 000 so'm",
//     monthly_payment: "1 560 so'm/oyiga",
//   },
//   {
//     id: 2,
//     img: "imgs/t_product_540_high.jpg (3).png",
//     isLiked: true,
//     title: `Smartfon Xiaomi Redmi Note 13, 6/128 GB, 8/128 GB, 8/256GB,…`,
//     reting: "4",
//     real_price: "3 010 000 so'm",
//     discount_price: "2 499 000 so'm",
//     monthly_payment: "299 880 so'm/oyiga",
//   },
//   {
//     id: 3,
//     img: "imgs/t_product_540_high.jpg (4).png",
//     isLiked: false,
//     title: `Kir yuvish kukuni Oila tanlovi "Ayoz tozaligi", avtomat, 3 kg`,
//     reting: "4",
//     real_price: "57 000 so'm",
//     discount_price: "41 000 so'm",
//     monthly_payment: "4 920 so'm/oyiga",
//   },
//   {
//     id: 4,
//     img: "imgs/t_product_540_high.jpg (5).png",
//     isLiked: false,
//     title: `Yangi tug'ilgan chaqaloqlar uchun
//       tana to'plami 100% paxta, 3 dona`,
//     reting: "4",
//     real_price: "160 000 so'm",
//     discount_price: "99 000 so'm",
//     monthly_payment: "11 880 so'm/oyiga",
//   },
//   {
//     id: 5,
//     img: "imgs/t_product_540_high.jpg (6).png",
//     isLiked: false,
//     title: `Sdobnoe pechenye Zarqand Brownie cookies, 490 g`,
//     reting: "4",
//     real_price: "1259 000 so'm34",
//     discount_price: "36 000 so'm",
//     monthly_payment: "4 320 so'm/oyiga",
//   },
//   {
//     id: 6,
//     img: "imgs/t_product_540_high.jpg (7).png",
//     isLiked: false,
//     title: `Televizor Samsung Crystal UHD 4K 43", 50", 55", 65" CU7100 Smart TV`,
//     reting: "4",
//     real_price: "5 830 000 so'm",
//     discount_price: "4 899 000 so'm",
//     monthly_payment: "587 880 so'm/oyiga",
//   },
//   {
//     id: 7,
//     img: "imgs/t_product_540_high.jpg (8).png",
//     isLiked: false,
//     title: `Avtomobil va uy uchun portativ, simsiz, kuchli JB-107 changyutgic…`,
//     reting: "4",
//     real_price: "199 000 so'm",
//     discount_price: "620 000 so'm",
//     monthly_payment: "23 880 so'm/oyiga",
//   },
//   {
//     id: 8,
//     img: "imgs/t_product_540_high.jpg (9).png",
//     isLiked: false,
//     title: `Sumka shopper ayollar uchun, yelkama, charmdan, eko zamsh,…`,
//     reting: "4",
//     real_price: "400 000 so'm",
//     discount_price: "99 000 so'm",
//     monthly_payment: "11 880 so'm/oyiga",
//   },
//   {
//     id: 9,
//     img: "imgs/t_product_540_high.jpg (10).png",
//     isLiked: false,
//     title: `Yostiqlar to'plami, bambukdan, gipoallergenli, ekologik toza, 70 *…`,
//     reting: "4",
//     real_price: "197 000 so'm",
//     discount_price: "89 000 so'm",
//     monthly_payment: "10 680 so'm/oyiga",
//   },
//   {
//     id: 10,
//     img: "imgs/t_product_540_high.jpg (11).png",
//     isLiked: false,
//     title: `Erkaklar uchun krossovka Joma r.vitaly men 2201 black`,
//     reting: "4",
//     real_price: "687 000 so'm",
//     discount_price: "349 000 so'm",
//     monthly_payment: "41 880 so'm/oyiga",
//   },
//   {
//     id: 10,
//     img: "imgs/t_product_540_high.jpg (11).png",
//     isLiked: false,
//     title: `Erkaklar uchun krossovka Joma r.vitaly men 2201 black`,
//     reting: "4",
//     real_price: "687 000 so'm",
//     discount_price: "349 000 so'm",
//     monthly_payment: "41 880 so'm/oyiga",
//   },
// ];

// localStorage.setItem("products", JSON.stringify(products));
